customer:
    resource: '@CustomerBundle/Controller/'
    type:   annotation

consumer:
    resource: '@ConsumerBundle/Controller/'
    type:   annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
