customer:
    resource: "@CustomerBundle/Controller/"
    prefix:   annotation

consumer:
    resource: "@ConsumerBundle/Controller/"
    prefix:   annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
