customer:
    resource: '@CustomerBundle/Controller/'
    type:   annotation

consumer:
    resource: '@ConsumerBundle/Controller/'
    type:   annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/online
