# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    address_checker:
      class: AppBundle\Services\AddressChecker

    app_bundle.doctrine_listener.customer_removal:
      class: AppBundle\EventListener\CustomerDeletionListener
      tags:
        - { name: doctrine.event_listener, event: preRemove }
